services:
  backend:
    build: ./Backend

  nginx:
    build: ./Frontend
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
