services:
  backend:
    build: ./Backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build: ./Frontend
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
